// Hardcoded, illustrative Hungarian simulation data. No network, no storage.
const sims = {
  0: {
    start: "Reggeli futás indítása",
    beforeLabel: "levél a közös postafiókban",
    total: 40,
    items: [
      { t: "Leállt a rendszer, nem tudunk dolgozni", s: "Dunavár Logisztika", cat: "m" },
      { t: "Számlán dupla tétel szerepel", s: "Kovács és Társa Kft.", cat: "m" },
      { t: "Azonnali szállítás kellene holnapra", s: "Pannon Webshop", cat: "m" },
      { t: "Árajánlat 200 db pólóra", s: "Rendezvény Bt.", cat: "c" },
      { t: "Együttműködési ajánlat", s: "Marketing Zrt.", cat: "c" },
      { t: "Számlázási cím módosítása", s: "Tóth Anna", cat: "c" },
      { t: "Hírlevél leiratkozás", s: "—", cat: "dim" },
      { t: "Automatikus válasz: szabadságon", s: "—", cat: "dim" },
      { t: "Reklám: SEO szolgáltatás", s: "—", cat: "dim" },
    ],
    afterHead: "3 sürgős levél vár ma reggel",
    picks: [
      { t: "Leállt a rendszer", reason: "Kiesés — ügyfélszolgálat, 4 órán belül", cat: "m" },
      { t: "Dupla számlatétel", reason: "Pénzügy — reklamáció", cat: "m" },
      { t: "Azonnali szállítás", reason: "Értékesítés — sürgős", cat: "m" },
    ],
    closing: "A maradék 37 levél nem sürgős.",
  },
  1: {
    start: "Napi érdeklődők feldolgozása",
    beforeLabel: "beérkező érdeklődő",
    total: 12,
    items: [
      { t: "Könyvelőiroda, 40 fő", s: "Van keret, idén indul, ő dönt", cat: "m" },
      { t: "Gyártó cég, dokumentum-automatizálás", s: "Döntéshozó, keret rendben", cat: "m" },
      { t: "Webshop ügyfélszolgálat", s: "Tulajdonos dönt, később", cat: "c" },
      { t: "Étterem foglalási rendszer", s: "Érdeklődik, nincs időpont", cat: "c" },
      { t: "Kisvállalkozás, hírlevél", s: "Kis keret", cat: "c" },
      { t: "Ingatlaniroda, chat", s: "Tájékozódik", cat: "c" },
      { t: "Egyetemista, szakdolgozat", s: "Nincs cég, ingyen kérné", cat: "dim" },
      { t: "Ügynökség, viszonteladás", s: "Nem illeszkedik", cat: "dim" },
      { t: "Álláskeresés", s: "Nem ügyfél", cat: "dim" },
    ],
    afterHead: "2 érdeklődőt hívj fel ma",
    picks: [
      { t: "Könyvelőiroda, 40 fő", reason: "A — keret, határidő, döntéshozó igazolt", cat: "m" },
      { t: "Gyártó cég", reason: "A — összetett igény, van büdzsé", cat: "m" },
    ],
    closing: "7 érdeklődő automatikus emailt kapott, 3 nem illeszkedik.",
  },
  3: {
    start: "Heti figyelés indítása",
    beforeLabel: "figyelt forrás",
    total: 6,
    items: [
      { t: "Fő versenytárs árlista", s: "+12% áremelés", cat: "m" },
      { t: "Jogszabály-adatbázis", s: "nincs változás", cat: "dim" },
      { t: "Közbeszerzési portál", s: "nincs változás", cat: "dim" },
      { t: "Iparági hírek", s: "nincs változás", cat: "dim" },
      { t: "Google Cégprofil", s: "nincs változás", cat: "dim" },
      { t: "Piaci elemzések", s: "nincs változás", cat: "dim" },
    ],
    afterHead: "1 dolog történt a héten: a fő versenytárs 12%-kal emelt árat.",
    picks: [
      { t: "Fő versenytárs", reason: "Árlista frissült — +12% a fő terméknél", cat: "m" },
    ],
    closing: "A többi 5 forráson nem történt semmi — ezért nem szóltunk.",
  },
  9: {
    start: "Pályázatok szűrése",
    beforeLabel: "önéletrajz egy pozícióra",
    total: 60,
    items: [
      { t: "8 releváns tapasztalat, pontos profil", s: "", cat: "c" },
      { t: "Erős szakmai háttér", s: "", cat: "c" },
      { t: "Illeszkedő készségek", s: "", cat: "c" },
      { t: "Részben illeszkedő", s: "", cat: "c" },
      { t: "Kevés tapasztalat", s: "", cat: "dim" },
      { t: "Más szakterület", s: "", cat: "dim" },
    ],
    afterHead: "8 jelölt jutott a szűrőn túl",
    afterBar: "Az agent nem utasít el senkit. A 60-ból mind a 60 megtekinthető, a döntést ember hozza.",
    picks: [
      { t: "1. jelölt", reason: "5 év releváns tapasztalat, pontos illeszkedés", cat: "c" },
      { t: "2. jelölt", reason: "Erős készségek, közeli helyszín", cat: "c" },
      { t: "3. jelölt", reason: "Vezető szerep a korábbi cégnél", cat: "c" },
    ],
    closing: "EU AI Act: audit-napló minden döntésről.",
  },
  10: {
    start: "Éjszakai riasztások feldolgozása",
    beforeLabel: "log sor éjszaka",
    total: 2400,
    items: [
      { t: "03:12 — szolgáltatás kiesés", s: "web-01", cat: "c" },
      { t: "04:41 — szolgáltatás kiesés", s: "web-03", cat: "c" },
      { t: "05:20 — ismeretlen adatbázis-hiba", s: "db-01", cat: "m" },
      { t: "INFO sorok", s: "rutin", cat: "dim" },
      { t: "DEBUG sorok", s: "rutin", cat: "dim" },
      { t: "Health-check", s: "rendben", cat: "dim" },
    ],
    afterHead: "2 riasztás automatikusan javítva (szolgáltatás újraindítva, 03:12 és 04:41). 1 riasztás felébresztett — ismeretlen hiba az adatbázisban.",
    picks: [
      { t: "03:12 kiesés", reason: "Ismert hiba — szolgáltatás újraindítva", cat: "c" },
      { t: "04:41 kiesés", reason: "Ismert hiba — szolgáltatás újraindítva", cat: "c" },
      { t: "DB hiba", reason: "Ismeretlen — ember kell, felébresztett", cat: "m" },
    ],
    closing: "Reggel 2400 sor helyett 3 mondat.",
  },
};

export default sims;
