// PARÁZS · tűzkonyha — kitalált márka.
const etterem = {
  hu: {
    seo: { title: "PARÁZS · tűzkonyha — AXIMBRA bemutató oldal", description: "Bemutató weboldal egy kitalált tűzkonyhás étteremnek: parázsanimáció, kóstolómenü, élő asztalfoglalás. Az AXIMBRA készítette." },
    brand: "PARÁZS", eyebrow: "Tűzkonyha · Belváros · csak vacsora",
    title: "Minden fogás a lángnál kezdődik.",
    sub: "Hétfogásos kóstolómenü nyílt tűzön, esténként tizennyolc vendégnek. Szezonális magyar alapanyag, semmi felesleges.",
    cta: "Asztalt foglalok", ghost: "A menü",
    menuTag: "Ősz", menuTitle: "A mostani kóstolómenü", menuSub: "Hét fogás, nagyjából két és fél óra. Húzd oldalra.",
    courses: [
      { n: "I", t: "Parázson sült cékla", d: "kecskesajt, fenyőrügy, füstölt olaj" },
      { n: "II", t: "Tiszai pisztráng", d: "nyírfán füstölve, tejföl, kapor" },
      { n: "III", t: "Hamuban sült zeller", d: "dióvaj, szarvasgomba, barnavaj" },
      { n: "IV", t: "Kenyér a kemencéből", d: "kovászos, mangalicazsír, lilahagyma" },
      { n: "V", t: "Mangalicatarja", d: "faszénen, birsalma, mustármag" },
      { n: "VI", t: "Szilva a tűzről", d: "tonkababos tejszín, mandula" },
      { n: "VII", t: "Füstös csokoládé", d: "sós karamell, pörkölt árpa" },
    ],
    price: "24 900 Ft / fő", pairing: "Borpárosítás: + 14 900 Ft",
    quote: "A tűz nem siet. Mi sem.", quoteBy: "a PARÁZS konyhája",
    feats: [
      { k: "8", t: "hely a séfpultnál", d: "Közvetlenül a tűz előtt ülsz, és látod, ahogy készül a vacsorád." },
      { k: "1", t: "fatüzelésű kemence", d: "Bükk és gyümölcsfa. Gáz nincs a konyhában." },
      { k: "100", t: "km-en belülről", d: "Minden alapanyagot ismert termelőtől veszünk, a közelből." },
    ],
    bookTag: "Foglalás", bookTitle: "Válassz estét", bookSub: "Esténként tizennyolc hely. A szabad időpontokat itt látod.",
    party: "Hány fő?", day: "Nap", time: "Időpont", left: "{n} hely", full: "telt ház",
    bookBtn: "Lefoglalom", confirm: "Asztal lefoglalva: {day}, {time}, {n} főre. A megerősítést SMS-ben küldtük.",
    confirmNote: "Bemutató: nem foglaltunk le semmit. Egy valódi oldalon ezt az AXIMBRA foglalási agentje kezeli, telefonon is.",
    again: "Másik időpont",
    address: "1052 Budapest, Képzelt utca 4.", phone: "+36 1 234 5678", email: "asztal@parazs-demo.hu",
    hours: "Sze–Szo 18:00–23:00",
    locale: "hu-HU",
  },
  en: {
    seo: { title: "PARÁZS · fire kitchen — AXIMBRA demo site", description: "A demo website for an invented fire-kitchen restaurant: ember animation, tasting menu, live table booking. Built by AXIMBRA." },
    brand: "PARÁZS", eyebrow: "Fire kitchen · Budapest · dinner only",
    title: "Every course starts at the flame.",
    sub: "A seven-course tasting menu cooked over open fire, for eighteen guests a night. Seasonal produce, nothing superfluous.",
    cta: "Book a table", ghost: "The menu",
    menuTag: "Autumn", menuTitle: "The current tasting menu", menuSub: "Seven courses, about two and a half hours. Swipe sideways.",
    courses: [
      { n: "I", t: "Ember-roasted beetroot", d: "goat's cheese, pine buds, smoked oil" },
      { n: "II", t: "River trout", d: "birch-smoked, sour cream, dill" },
      { n: "III", t: "Celeriac baked in ash", d: "walnut butter, truffle, brown butter" },
      { n: "IV", t: "Bread from the oven", d: "sourdough, mangalica lard, red onion" },
      { n: "V", t: "Mangalica pork neck", d: "over charcoal, quince, mustard seed" },
      { n: "VI", t: "Plums from the fire", d: "tonka cream, almond" },
      { n: "VII", t: "Smoky chocolate", d: "salted caramel, roasted barley" },
    ],
    price: "€69 per guest", pairing: "Wine pairing: + €42",
    quote: "Fire doesn't hurry. Neither do we.", quoteBy: "the PARÁZS kitchen",
    feats: [
      { k: "8", t: "seats at the chef's counter", d: "Right in front of the fire, watching your dinner being made." },
      { k: "1", t: "wood-fired oven", d: "Beech and fruitwood. There is no gas in the kitchen." },
      { k: "100", t: "km radius", d: "Every ingredient comes from a grower we know, close by." },
    ],
    bookTag: "Booking", bookTitle: "Choose your evening", bookSub: "Eighteen seats a night. Free times are shown live.",
    party: "Guests", day: "Day", time: "Time", left: "{n} seats", full: "full",
    bookBtn: "Book it", confirm: "Table booked: {day}, {time}, for {n}. We've texted you the confirmation.",
    confirmNote: "Demo: nothing was booked. On a real site the AXIMBRA booking agent handles this — by phone too.",
    again: "Pick another time",
    address: "Imaginary Street 4, 1052 Budapest", phone: "+36 1 234 5678", email: "table@parazs-demo.hu",
    hours: "Wed–Sat 18:00–23:00",
    locale: "en-GB",
  },
  de: {
    seo: { title: "PARÁZS · Feuerküche — AXIMBRA Demo-Seite", description: "Demo-Website eines erfundenen Feuerküchen-Restaurants: Glutanimation, Degustationsmenü, Live-Tischreservierung. Erstellt von AXIMBRA." },
    brand: "PARÁZS", eyebrow: "Feuerküche · Budapest · nur abends",
    title: "Jeder Gang beginnt an der Flamme.",
    sub: "Ein Degustationsmenü in sieben Gängen über offenem Feuer, für achtzehn Gäste am Abend. Saisonal, regional, nichts Überflüssiges.",
    cta: "Tisch reservieren", ghost: "Das Menü",
    menuTag: "Herbst", menuTitle: "Das aktuelle Menü", menuSub: "Sieben Gänge, etwa zweieinhalb Stunden. Seitlich wischen.",
    courses: [
      { n: "I", t: "Rote Bete aus der Glut", d: "Ziegenkäse, Fichtenspitzen, Rauchöl" },
      { n: "II", t: "Flussforelle", d: "über Birke geräuchert, Schmand, Dill" },
      { n: "III", t: "Sellerie in der Asche", d: "Walnussbutter, Trüffel, Nussbutter" },
      { n: "IV", t: "Brot aus dem Ofen", d: "Sauerteig, Mangalica-Schmalz, rote Zwiebel" },
      { n: "V", t: "Mangalica-Nacken", d: "über Holzkohle, Quitte, Senfsaat" },
      { n: "VI", t: "Pflaumen vom Feuer", d: "Tonkacreme, Mandel" },
      { n: "VII", t: "Rauchige Schokolade", d: "Salzkaramell, geröstete Gerste" },
    ],
    price: "69 € pro Person", pairing: "Weinbegleitung: + 42 €",
    quote: "Feuer hat keine Eile. Wir auch nicht.", quoteBy: "die Küche von PARÁZS",
    feats: [
      { k: "8", t: "Plätze am Küchentresen", d: "Direkt vor dem Feuer — Sie sehen, wie Ihr Abendessen entsteht." },
      { k: "1", t: "Holzofen", d: "Buche und Obstholz. In unserer Küche gibt es kein Gas." },
      { k: "100", t: "km Umkreis", d: "Jede Zutat stammt von Erzeugern, die wir kennen." },
    ],
    bookTag: "Reservierung", bookTitle: "Wählen Sie Ihren Abend", bookSub: "Achtzehn Plätze pro Abend. Freie Zeiten sehen Sie hier live.",
    party: "Personen", day: "Tag", time: "Uhrzeit", left: "{n} Plätze", full: "ausgebucht",
    bookBtn: "Reservieren", confirm: "Tisch reserviert: {day}, {time}, für {n} Personen. Die Bestätigung kam per SMS.",
    confirmNote: "Demo: Es wurde nichts reserviert. Auf einer echten Seite übernimmt das der Buchungsagent von AXIMBRA — auch am Telefon.",
    again: "Andere Zeit wählen",
    address: "Musterstraße 4, 1052 Budapest", phone: "+36 1 234 5678", email: "tisch@parazs-demo.hu",
    hours: "Mi–Sa 18:00–23:00",
    locale: "de-DE",
  },
};
export default etterem;
