// LUMEN Fogászat — kitalált márka. Árak, címek, munkatársak: mind kitalált.
const fogaszat = {
  hu: {
    seo: { title: "LUMEN Fogászat — AXIMBRA bemutató oldal", description: "Bemutató weboldal egy kitalált fogászatnak: animált fog, árkalkulátor, AI-recepció. Az AXIMBRA készítette." },
    brand: "LUMEN", brandSub: "Fogászat",
    nav: ["Kezelések", "Árak", "Időpont"],
    eyebrow: "Esztétikai és általános fogászat · Budapest XI.",
    title: "Mosolyogj úgy, mintha senki nem nézné.",
    sub: "Fájdalommentes kezelés, előre leírt árak, és egy csapat, amely előbb meghallgat, aztán kezel.",
    cta: "Időpontot kérek", ghost: "Mennyibe kerülne?",
    chips: ["Szombaton is rendelünk", "Altatásos kezelés", "Árajánlat 24 órán belül"],
    fearTag: "Félsz a fogorvostól?",
    fearTitle: "Nem vagy egyedül. Nálunk ez a kiindulópont.",
    fearText: "Minden második páciensünk szorongva érkezik. Ezért nálunk semmi nem történik meglepetésből.",
    fearPoints: ["Minden lépést előre elmondunk, a kezelés közben is.", "Egy kézfeltartással bármikor megállíthatod.", "Érzéstelenítés, ami tényleg hat — és altatás, ha kell."],
    breath: ["Lélegezz be", "Tartsd bent", "Fújd ki"],
    breathNote: "Próbáld ki most: kövesd a kört négy ütemen át.",
    treatTitle: "Kezelések", treatSub: "Amit a leggyakrabban kérnek tőlünk.",
    treatments: [
      { icon: "spark", t: "Fogfehérítés", d: "Rendelői, egy ülésben, érzékenység nélkül.", p: "49 000 Ft-tól" },
      { icon: "implant", t: "Implantátum", d: "3D-s CT alapján tervezve, élethosszig tartó garanciával.", p: "290 000 Ft-tól" },
      { icon: "aligner", t: "Láthatatlan fogszabályozó", d: "Átlátszó sín, digitális lenyomattal, fém nélkül.", p: "690 000 Ft-tól" },
      { icon: "veneer", t: "Kerámia héj", d: "Vékony porcelán réteg a tökéletes formáért.", p: "120 000 Ft / fog" },
      { icon: "clean", t: "Dentálhigiénia", d: "Fogkőeltávolítás, polírozás, otthoni tanácsok.", p: "22 000 Ft" },
      { icon: "kid", t: "Gyermekfogászat", d: "Játékos első látogatás, hogy ne legyen félelem.", p: "15 000 Ft" },
    ],
    baTitle: "Húzd el, és nézd a különbséget", baBefore: "Előtte", baAfter: "Utána", baNote: "Illusztráció, nem valódi páciens.",
    estTitle: "Mennyibe kerülne?", estSub: "Jelöld be, ami érdekel — azonnal látod a becsült keretet.",
    est: [
      { t: "Fogfehérítés", min: 49000, max: 79000 },
      { t: "Dentálhigiénia", min: 22000, max: 28000 },
      { t: "Kerámia héj, 2 fog", min: 240000, max: 300000 },
      { t: "Egy implantátum koronával", min: 290000, max: 420000 },
      { t: "Láthatatlan fogszabályozó", min: 690000, max: 1100000 },
    ],
    estTotal: "Becsült keret", estEmpty: "Válassz legalább egy kezelést.", estCta: "Pontos árajánlatot kérek",
    estNote: "A végleges ár a konzultáción, röntgen alapján derül ki — és írásban kapod meg.",
    cur: "HUF",
    recTitle: "Írj a recepciónak. Éjjel is válaszol.",
    recSub: "Időpont, sürgős fájdalom, árkérdés: a recepció azonnal válaszol, és lefoglalja a szabad időpontot.",
    recBadge: "Ezt a recepciót az AXIMBRA AI-agentje viszi",
    script: [
      { from: "user", text: "Szia! Nagyon fáj a bal alsó fogam. Mikor tudnátok fogadni?" },
      { from: "bot", text: "Sajnálom, hogy fáj. Holnap 8:30-kor és 14:00-kor van szabad sürgősségi időpont. Melyik jó?" },
      { from: "user", text: "A 8:30 jó lesz." },
      { from: "bot", text: "Lefoglaltam holnap 8:30-ra. SMS-ben küldöm a megerősítést és az útvonalat. Addig fájdalomcsillapító szedhető, a dózist a dobozon nézd meg." },
    ],
    faqTitle: "Gyakori kérdések",
    faq: [
      { q: "Fáj a fogfehérítés?", a: "Nem. Érzékeny fogaknál előtte deszenzibilizáló gélt használunk, így a kezelés után sem húzódik." },
      { q: "Mennyi idő egy implantátum?", a: "A beültetés egy ülés. A csont gyógyulása 3–4 hónap, utána kerül fel a végleges korona." },
      { q: "Részletre is fizethetek?", a: "Igen, 6 vagy 12 hónapos kamatmentes részletfizetéssel, 150 000 Ft feletti kezeléseknél." },
    ],
    contactTitle: "Időpontkérés",
    contactSub: "Írd meg, mi a gond, és egy munkanapon belül visszahívunk a legközelebbi szabad időponttal.",
    address: "1117 Budapest, Képzelt körút 8.", phone: "+36 1 345 6789", email: "rendelo@lumen-demo.hu",
    hours: "H–P 8:00–20:00 · Szo 9:00–14:00",
    formName: "Név", formContact: "Telefon vagy e-mail", formMsg: "Mi a panasz, vagy mi érdekel?", formSend: "Időpontot kérek",
  },
  en: {
    seo: { title: "LUMEN Dental — AXIMBRA demo site", description: "A demo website for an invented dental clinic: animated tooth, price estimator, AI reception. Built by AXIMBRA." },
    brand: "LUMEN", brandSub: "Dental",
    nav: ["Treatments", "Prices", "Book"],
    eyebrow: "Cosmetic & general dentistry · Budapest",
    title: "Smile like nobody's watching.",
    sub: "Pain-free treatment, prices written down up front, and a team that listens first and treats second.",
    cta: "Book an appointment", ghost: "What would it cost?",
    chips: ["Open on Saturdays", "Sedation available", "Quote within 24 hours"],
    fearTag: "Afraid of the dentist?",
    fearTitle: "You're not alone. That's where we start.",
    fearText: "Every second patient arrives anxious. So nothing here ever happens as a surprise.",
    fearPoints: ["We explain every step before it happens — and during it.", "Raise your hand and we stop. Any time.", "Anaesthesia that actually works — and sedation if you need it."],
    breath: ["Breathe in", "Hold", "Breathe out"],
    breathNote: "Try it now: follow the circle for four rounds.",
    treatTitle: "Treatments", treatSub: "What people ask us for most.",
    treatments: [
      { icon: "spark", t: "Teeth whitening", d: "In-clinic, one session, no sensitivity.", p: "from €129" },
      { icon: "implant", t: "Dental implant", d: "Planned from a 3D CT scan, with a lifetime guarantee.", p: "from €790" },
      { icon: "aligner", t: "Invisible aligners", d: "Clear trays from a digital scan, no metal.", p: "from €1,890" },
      { icon: "veneer", t: "Porcelain veneers", d: "A thin ceramic layer for the perfect shape.", p: "€320 / tooth" },
      { icon: "clean", t: "Hygiene visit", d: "Scaling, polishing and advice for home.", p: "€59" },
      { icon: "kid", t: "Children's dentistry", d: "A playful first visit, so fear never starts.", p: "€39" },
    ],
    baTitle: "Drag to see the difference", baBefore: "Before", baAfter: "After", baNote: "Illustration, not a real patient.",
    estTitle: "What would it cost?", estSub: "Tick what interests you — the estimated range updates instantly.",
    est: [
      { t: "Teeth whitening", min: 129, max: 209 },
      { t: "Hygiene visit", min: 59, max: 75 },
      { t: "Porcelain veneers, 2 teeth", min: 640, max: 800 },
      { t: "One implant with crown", min: 790, max: 1150 },
      { t: "Invisible aligners", min: 1890, max: 2990 },
    ],
    estTotal: "Estimated range", estEmpty: "Pick at least one treatment.", estCta: "Get an exact quote",
    estNote: "The final price is set at the consultation, based on an X-ray — and you get it in writing.",
    cur: "EUR",
    recTitle: "Message reception. It answers at night too.",
    recSub: "Appointments, sudden pain, price questions: reception replies at once and books the free slot.",
    recBadge: "This reception is run by an AXIMBRA AI agent",
    script: [
      { from: "user", text: "Hi! My lower left tooth really hurts. When could you see me?" },
      { from: "bot", text: "Sorry to hear that. There are emergency slots tomorrow at 8:30 and 14:00. Which works?" },
      { from: "user", text: "8:30, please." },
      { from: "bot", text: "Booked for tomorrow 8:30. I'm texting you the confirmation and directions. Until then you can take a painkiller — check the dose on the box." },
    ],
    faqTitle: "Questions people ask",
    faq: [
      { q: "Does whitening hurt?", a: "No. For sensitive teeth we apply a desensitising gel first, so there's no twinge afterwards either." },
      { q: "How long does an implant take?", a: "Placing it is one visit. The bone heals in 3–4 months, then the final crown goes on." },
      { q: "Can I pay in instalments?", a: "Yes — 6 or 12 months interest-free on treatments over €400." },
    ],
    contactTitle: "Request an appointment",
    contactSub: "Tell us what's wrong and we'll call you back within one working day with the next free slot.",
    address: "Imaginary Boulevard 8, 1117 Budapest", phone: "+36 1 345 6789", email: "clinic@lumen-demo.hu",
    hours: "Mon–Fri 8:00–20:00 · Sat 9:00–14:00",
    formName: "Name", formContact: "Phone or email", formMsg: "What's the problem, or what are you interested in?", formSend: "Request appointment",
  },
  de: {
    seo: { title: "LUMEN Zahnarztpraxis — AXIMBRA Demo-Seite", description: "Demo-Website einer erfundenen Zahnarztpraxis: animierter Zahn, Kostenrechner, KI-Rezeption. Erstellt von AXIMBRA." },
    brand: "LUMEN", brandSub: "Zahnarztpraxis",
    nav: ["Behandlungen", "Preise", "Termin"],
    eyebrow: "Ästhetische & allgemeine Zahnmedizin",
    title: "Lächeln Sie, als würde niemand hinsehen.",
    sub: "Schmerzfreie Behandlung, Preise vorab schriftlich und ein Team, das erst zuhört und dann behandelt.",
    cta: "Termin anfragen", ghost: "Was würde es kosten?",
    chips: ["Auch samstags geöffnet", "Behandlung in Sedierung", "Kostenvoranschlag in 24 Stunden"],
    fearTag: "Angst vor dem Zahnarzt?",
    fearTitle: "Sie sind nicht allein. Genau dort fangen wir an.",
    fearText: "Jeder zweite Patient kommt mit einem mulmigen Gefühl. Deshalb passiert bei uns nichts überraschend.",
    fearPoints: ["Wir erklären jeden Schritt vorher — und währenddessen.", "Heben Sie die Hand, und wir hören sofort auf.", "Eine Betäubung, die wirklich wirkt — und Sedierung, wenn nötig."],
    breath: ["Einatmen", "Halten", "Ausatmen"],
    breathNote: "Probieren Sie es jetzt: Folgen Sie dem Kreis vier Runden lang.",
    treatTitle: "Behandlungen", treatSub: "Was am häufigsten bei uns angefragt wird.",
    treatments: [
      { icon: "spark", t: "Bleaching", d: "In der Praxis, eine Sitzung, ohne Empfindlichkeit.", p: "ab 129 €" },
      { icon: "implant", t: "Implantat", d: "Geplant nach 3D-CT, mit lebenslanger Garantie.", p: "ab 790 €" },
      { icon: "aligner", t: "Unsichtbare Zahnspange", d: "Transparente Schienen nach digitalem Scan, ohne Metall.", p: "ab 1.890 €" },
      { icon: "veneer", t: "Keramik-Veneers", d: "Eine dünne Keramikschale für die perfekte Form.", p: "320 € / Zahn" },
      { icon: "clean", t: "Professionelle Zahnreinigung", d: "Zahnstein, Politur und Tipps für zu Hause.", p: "59 €" },
      { icon: "kid", t: "Kinderzahnheilkunde", d: "Ein spielerischer erster Besuch, damit Angst gar nicht entsteht.", p: "39 €" },
    ],
    baTitle: "Ziehen Sie und sehen Sie den Unterschied", baBefore: "Vorher", baAfter: "Nachher", baNote: "Illustration, kein echter Patient.",
    estTitle: "Was würde es kosten?", estSub: "Kreuzen Sie an, was Sie interessiert — die geschätzte Spanne erscheint sofort.",
    est: [
      { t: "Bleaching", min: 129, max: 209 },
      { t: "Professionelle Zahnreinigung", min: 59, max: 75 },
      { t: "Keramik-Veneers, 2 Zähne", min: 640, max: 800 },
      { t: "Ein Implantat mit Krone", min: 790, max: 1150 },
      { t: "Unsichtbare Zahnspange", min: 1890, max: 2990 },
    ],
    estTotal: "Geschätzte Spanne", estEmpty: "Wählen Sie mindestens eine Behandlung.", estCta: "Genauen Kostenvoranschlag anfordern",
    estNote: "Der endgültige Preis steht nach der Beratung und dem Röntgenbild fest — schriftlich.",
    cur: "EUR",
    recTitle: "Schreiben Sie der Rezeption. Sie antwortet auch nachts.",
    recSub: "Termine, akute Schmerzen, Preisfragen: Die Rezeption antwortet sofort und bucht den freien Termin.",
    recBadge: "Diese Rezeption führt ein KI-Agent von AXIMBRA",
    script: [
      { from: "user", text: "Hallo! Mein Zahn unten links tut sehr weh. Wann hätten Sie Zeit?" },
      { from: "bot", text: "Das tut mir leid. Morgen um 8:30 und um 14:00 gibt es freie Notfalltermine. Was passt Ihnen?" },
      { from: "user", text: "8:30 bitte." },
      { from: "bot", text: "Gebucht für morgen 8:30. Die Bestätigung und die Anfahrt kommen per SMS. Bis dahin hilft ein Schmerzmittel — die Dosis steht auf der Packung." },
    ],
    faqTitle: "Häufige Fragen",
    faq: [
      { q: "Tut Bleaching weh?", a: "Nein. Bei empfindlichen Zähnen tragen wir vorher ein desensibilisierendes Gel auf, sodass auch danach nichts zieht." },
      { q: "Wie lange dauert ein Implantat?", a: "Das Einsetzen ist eine Sitzung. Der Knochen heilt in 3–4 Monaten, danach kommt die endgültige Krone." },
      { q: "Kann ich in Raten zahlen?", a: "Ja — 6 oder 12 Monate zinsfrei bei Behandlungen über 400 €." },
    ],
    contactTitle: "Termin anfragen",
    contactSub: "Schreiben Sie uns, was los ist — wir rufen Sie innerhalb eines Werktags mit dem nächsten freien Termin zurück.",
    address: "Musterallee 8, 1117 Budapest", phone: "+36 1 345 6789", email: "praxis@lumen-demo.hu",
    hours: "Mo–Fr 8:00–20:00 · Sa 9:00–14:00",
    formName: "Name", formContact: "Telefon oder E-Mail", formMsg: "Was ist los, oder was interessiert Sie?", formSend: "Termin anfragen",
  },
};
export default fogaszat;
