// VERITAS Ügyvédi Iroda — kitalált márka.
const ugyvedi = {
  hu: {
    seo: { title: "VERITAS Ügyvédi Iroda — AXIMBRA bemutató oldal", description: "Bemutató weboldal egy kitalált ügyvédi irodának: mozgó mérleg, 60 másodperces ügyfelmérő, átlátható díjak. Az AXIMBRA készítette." },
    brand: "VERITAS", brandSub: "Ügyvédi Iroda",
    eyebrow: "Gazdasági, ingatlan- és munkajog · Budapest V.",
    title: "Erős érvek. Nyugodt ügyfelek.",
    sub: "Világos díjazás, írásban rögzített határidők, és mindig tudod, hol tart az ügyed.",
    cta: "Ügyfelmérés 60 mp alatt", ghost: "Szakterületek",
    triTag: "Ügyfelmérő", triTitle: "Merre billen az ügyed?", triSub: "Három kérdés, és megmondjuk, melyik csapatunk illik hozzád, és mennyire sürgős.",
    step: "Kérdés {i} / {n}",
    qs: [
      { q: "Milyen ügyről van szó?", opts: ["Cégügy, szerződés", "Ingatlan", "Munkajog", "Család, öröklés"] },
      { q: "Van határidő?", opts: ["Igen, 8 napon belül", "Igen, 30 napon belül", "Nincs, vagy nem tudom"] },
      { q: "Hol tart most?", opts: ["Még csak tájékozódom", "Kaptam egy levelet vagy felszólítást", "Már per van folyamatban"] },
    ],
    teams: ["gazdasági jogi csoport", "ingatlanjogi csoport", "munkajogi csoport", "családjogi csoport"],
    urg: ["Sürgős — még ma visszahívunk.", "Kiemelt — 24 órán belül jelentkezünk.", "Normál — két munkanapon belül egyeztetünk."],
    resTitle: "Javaslatunk", resTeam: "Neked a {team} való.", resCta: "Visszahívást kérek", restart: "Újrakezdem",
    resNote: "Egy valódi oldalon ezt a felmérést az AXIMBRA érdeklődő-minősítő agentje végzi, és a sürgős ügyeket azonnal jelzi az irodának.",
    areasTitle: "Szakterületek",
    areas: [
      { t: "Gazdasági jog", d: "Cégalapítás, szerződések, követeléskezelés, társasági viták." },
      { t: "Ingatlanjog", d: "Adásvétel, bérlet, társasház, építési szerződések." },
      { t: "Munkajog", d: "Felmondás, munkaszerződés, munkaügyi per mindkét oldalon." },
      { t: "Családjog és öröklés", d: "Házassági vagyonjog, válás, végrendelet, hagyatéki eljárás." },
    ],
    feeTitle: "Díjazás, meglepetések nélkül",
    fees: [
      { t: "Első konzultáció", p: "25 000 Ft", d: "30 perc. Ha megbízol minket, beszámítjuk a díjba." },
      { t: "Fix díjas ügyek", p: "előre rögzített ár", d: "Szerződés, cégalapítás, ingatlan-adásvétel: az árat az elején leírjuk." },
      { t: "Óradíjas képviselet", p: "45 000 Ft / óra", d: "Havonta tételes kimutatással: mit, mikor, mennyi ideig." },
    ],
    procTitle: "Így dolgozunk",
    proc: [
      { t: "Meghallgatunk", d: "Az első beszélgetésen kiderül, van-e ügyed, és mennyibe kerülhet." },
      { t: "Írásba tesszük", d: "Megbízási szerződés: díj, határidők, ki felel érted az irodában." },
      { t: "Képviselünk", d: "Minden lépés után rövid összefoglalót kapsz, jogi nyelv nélkül." },
      { t: "Lezárjuk", d: "Átadjuk az iratokat, és megmondjuk, mire figyelj a jövőben." },
    ],
    contactTitle: "Visszahívást kérek",
    contactSub: "Írd le röviden az ügyedet. Az első választ egy munkanapon belül kapod, sürgős ügyben még aznap.",
    address: "1054 Budapest, Képzelt tér 2.", phone: "+36 1 567 8901", email: "iroda@veritas-demo.hu", hours: "H–P 9:00–18:00",
    formName: "Név", formContact: "Telefon vagy e-mail", formMsg: "Röviden az ügyről", formSend: "Visszahívást kérek",
  },
  en: {
    seo: { title: "VERITAS Law Firm — AXIMBRA demo site", description: "A demo website for an invented law firm: moving scales, a 60-second case check, transparent fees. Built by AXIMBRA." },
    brand: "VERITAS", brandSub: "Law Firm",
    eyebrow: "Corporate, property & employment law · Budapest",
    title: "Strong arguments. Calm clients.",
    sub: "Clear fees, deadlines in writing, and you always know where your case stands.",
    cta: "60-second case check", ghost: "Practice areas",
    triTag: "Case check", triTitle: "Which way does your case tip?", triSub: "Three questions, and we'll tell you which team fits and how urgent it is.",
    step: "Question {i} / {n}",
    qs: [
      { q: "What is it about?", opts: ["Business, contracts", "Property", "Employment", "Family, inheritance"] },
      { q: "Is there a deadline?", opts: ["Yes, within 8 days", "Yes, within 30 days", "No, or I don't know"] },
      { q: "Where are you now?", opts: ["Just looking into it", "I received a letter or demand", "Proceedings have started"] },
    ],
    teams: ["corporate team", "property team", "employment team", "family law team"],
    urg: ["Urgent — we'll call you back today.", "Priority — we'll be in touch within 24 hours.", "Standard — we'll arrange a call within two working days."],
    resTitle: "Our recommendation", resTeam: "Our {team} is the right fit.", resCta: "Request a call back", restart: "Start over",
    resNote: "On a real site this check is run by the AXIMBRA lead-qualifier agent, which flags urgent cases to the firm straight away.",
    areasTitle: "Practice areas",
    areas: [
      { t: "Corporate law", d: "Company formation, contracts, debt recovery, shareholder disputes." },
      { t: "Property law", d: "Sales, leases, condominiums, construction contracts." },
      { t: "Employment law", d: "Dismissals, contracts, tribunal cases — for either side." },
      { t: "Family & inheritance", d: "Marital property, divorce, wills, probate." },
    ],
    feeTitle: "Fees without surprises",
    fees: [
      { t: "First consultation", p: "€70", d: "30 minutes. Credited to your fee if you instruct us." },
      { t: "Fixed-fee matters", p: "price set up front", d: "Contracts, formations, property sales: the price is written down at the start." },
      { t: "Hourly representation", p: "€125 / hour", d: "Itemised monthly: what, when and for how long." },
    ],
    procTitle: "How we work",
    proc: [
      { t: "We listen", d: "The first conversation shows whether you have a case and what it may cost." },
      { t: "We put it in writing", d: "An engagement letter: fees, deadlines, who is responsible for you." },
      { t: "We represent you", d: "After every step you get a short summary, free of legal jargon." },
      { t: "We close it", d: "We hand over the files and tell you what to watch for in future." },
    ],
    contactTitle: "Request a call back",
    contactSub: "Describe your matter briefly. You'll hear from us within one working day — the same day if it's urgent.",
    address: "Imaginary Square 2, 1054 Budapest", phone: "+36 1 567 8901", email: "office@veritas-demo.hu", hours: "Mon–Fri 9:00–18:00",
    formName: "Name", formContact: "Phone or email", formMsg: "Your matter in brief", formSend: "Request a call back",
  },
  de: {
    seo: { title: "VERITAS Rechtsanwälte — AXIMBRA Demo-Seite", description: "Demo-Website einer erfundenen Kanzlei: bewegte Waage, 60-Sekunden-Fallcheck, transparente Honorare. Erstellt von AXIMBRA." },
    brand: "VERITAS", brandSub: "Rechtsanwälte",
    eyebrow: "Wirtschafts-, Immobilien- & Arbeitsrecht",
    title: "Starke Argumente. Ruhige Mandanten.",
    sub: "Klare Honorare, Fristen schriftlich festgehalten, und Sie wissen immer, wo Ihr Fall steht.",
    cta: "Fallcheck in 60 Sekunden", ghost: "Rechtsgebiete",
    triTag: "Fallcheck", triTitle: "Wohin neigt sich Ihr Fall?", triSub: "Drei Fragen — und wir sagen Ihnen, welches Team passt und wie dringend es ist.",
    step: "Frage {i} / {n}",
    qs: [
      { q: "Worum geht es?", opts: ["Unternehmen, Verträge", "Immobilien", "Arbeitsrecht", "Familie, Erbrecht"] },
      { q: "Gibt es eine Frist?", opts: ["Ja, innerhalb von 8 Tagen", "Ja, innerhalb von 30 Tagen", "Nein, oder weiß nicht"] },
      { q: "Wo stehen Sie gerade?", opts: ["Ich informiere mich erst", "Ich habe ein Schreiben oder eine Mahnung erhalten", "Ein Verfahren läuft bereits"] },
    ],
    teams: ["Team Wirtschaftsrecht", "Team Immobilienrecht", "Team Arbeitsrecht", "Team Familienrecht"],
    urg: ["Dringend — wir rufen Sie heute noch zurück.", "Vorrangig — wir melden uns innerhalb von 24 Stunden.", "Normal — wir vereinbaren innerhalb von zwei Werktagen einen Termin."],
    resTitle: "Unsere Empfehlung", resTeam: "Für Sie passt unser {team}.", resCta: "Rückruf anfordern", restart: "Neu starten",
    resNote: "Auf einer echten Seite übernimmt diesen Check der Lead-Qualifizierer von AXIMBRA und meldet dringende Fälle sofort an die Kanzlei.",
    areasTitle: "Rechtsgebiete",
    areas: [
      { t: "Wirtschaftsrecht", d: "Gründung, Verträge, Forderungsmanagement, Gesellschafterstreit." },
      { t: "Immobilienrecht", d: "Kauf, Miete, Wohnungseigentum, Bauverträge." },
      { t: "Arbeitsrecht", d: "Kündigung, Arbeitsvertrag, Arbeitsgerichtsverfahren — für beide Seiten." },
      { t: "Familien- & Erbrecht", d: "Güterrecht, Scheidung, Testament, Nachlass." },
    ],
    feeTitle: "Honorare ohne Überraschungen",
    fees: [
      { t: "Erstberatung", p: "70 €", d: "30 Minuten. Wird bei Mandatierung angerechnet." },
      { t: "Pauschalmandate", p: "Festpreis vorab", d: "Verträge, Gründungen, Immobilienkauf: Der Preis steht am Anfang schriftlich fest." },
      { t: "Stundenhonorar", p: "125 € / Stunde", d: "Monatlich aufgeschlüsselt: was, wann, wie lange." },
    ],
    procTitle: "So arbeiten wir",
    proc: [
      { t: "Zuhören", d: "Im ersten Gespräch klären wir, ob Sie einen Fall haben und was er kosten kann." },
      { t: "Schriftlich festhalten", d: "Mandatsvereinbarung: Honorar, Fristen, Ihr Ansprechpartner." },
      { t: "Vertreten", d: "Nach jedem Schritt eine kurze Zusammenfassung — ohne Juristendeutsch." },
      { t: "Abschließen", d: "Wir übergeben die Akten und sagen Ihnen, worauf Sie künftig achten sollten." },
    ],
    contactTitle: "Rückruf anfordern",
    contactSub: "Beschreiben Sie Ihr Anliegen kurz. Sie hören innerhalb eines Werktags von uns — in dringenden Fällen am selben Tag.",
    address: "Musterplatz 2, 1054 Budapest", phone: "+36 1 567 8901", email: "kanzlei@veritas-demo.hu", hours: "Mo–Fr 9:00–18:00",
    formName: "Name", formContact: "Telefon oder E-Mail", formMsg: "Ihr Anliegen in Kürze", formSend: "Rückruf anfordern",
  },
};
export default ugyvedi;
