// ŐRLŐ kávépörkölő — kitalált webshop.
const webshop = {
  hu: {
    heroAgent: "AI-ügyfélszolgálat kipróbálása",
    liveStep1: "1. Adj le egy próbarendelést a saját e-mail-címedre", liveOrderBtn: "Próbarendelés", liveOrdering: "Rendelés…",
    liveOrdered: "Kész: a(z) {n} rendelés a(z) {e} címre ment. Most kérdezd meg az agentet, hol tart!",
    liveStep2: "2. Írj az ügyfélszolgálatnak", liveAsk: "Szia! Hol tart a(z) {n} rendelésem?", liveStranger: "Próbáld ki idegen címmel is", liveOther: "Mintalevelek",
    liveTag: "Élő AI-agent", liveTitle: "Írj az ügyfélszolgálatnak", liveSub: "Ez már nem bemutató szöveg: a valódi AXIMBRA webshop-agent olvassa el a leveledet, megkeresi a rendelést, és megírja a választervezetet. Egy éles boltban ezt egy munkatárs hagyná jóvá.",
    liveFrom: "Feladó e-mail-címe", liveMsg: "Üzenet", liveSend: "Elküldöm", liveSending: "Az agent dolgozik…",
    liveDraft: "Az agent választervezete", liveOk: "Azonosított vásárló", liveNo: "Nem a rendelő címe – adatot nem ad ki", liveNone: "Nincs ilyen rendelés",
    liveHuman: "Munkatárs nézze át", liveErr: "Most nem érem el az agentet. Próbáld újra egy perc múlva.",
    liveHint: "Próbáld ki: a rendelő címével megkapod a csomag adatait, más címmel nem.",
    liveSamples: [["anna.kovacs@example.com", "Szia! Hol tart az ORL-1042 rendelésem? Holnapra kellene ajándékba."], ["valaki@gmail.com", "Hol tart az ORL-1042 rendelés?"], ["peter.nagy@example.com", "Az ORL-1043 csomagot vissza szeretném küldeni, hogyan tehetem meg?"]],
    seo: { title: "ŐRLŐ kávépörkölő — AXIMBRA bemutató webshop", description: "Bemutató webshop egy kitalált kávépörkölőnek: pörkölési csúszka, kosár, csomagkövetés ügyfélszolgálati AI-agenttel. Az AXIMBRA készítette." },
    brand: "ŐRLŐ", brandSub: "kávépörkölő",
    ship: "Ingyenes szállítás {x} felett · 48 órán belül pörkölve küldjük",
    eyebrow: "Specialty kávé · kis tételben pörkölve",
    title: "Frissen pörkölve. Holnap nálad.",
    sub: "Nyomon követhető farmokról, hetente pörkölve, a pörkölés után 48 órán belül postázva.",
    cta: "Kávét választok", ghost: "Hol a csomagom?",
    roastTag: "Ízkereső", roastTitle: "Milyen pörkölést szeretsz?", roastSub: "Húzd a csúszkát — megmutatjuk az ízjegyeket és a hozzád illő kávét.",
    roasts: [
      { n: "Világos", notes: ["jázmin", "citrus", "fekete tea"], hint: "Filteres kávéhoz, tiszta, gyümölcsös csésze." },
      { n: "Közepes", notes: ["karamell", "alma", "tejcsokoládé"], hint: "Mindenre jó: filter, mokka, tejes ital." },
      { n: "Sötét", notes: ["étcsokoládé", "dió", "melasz"], hint: "Espressóhoz és tejes italokhoz, testes, édes." },
    ],
    match: "Neked ajánljuk:",
    shopTitle: "A heti pörkölés", add: "Kosárba", added: "Hozzáadva",
    products: [
      { id: "eti", n: "Etiópia Guji", o: "Etiópia · mosott", r: 0, notes: "barack, jázmin, bergamott", p: 5900 },
      { id: "kol", n: "Kolumbia Huila", o: "Kolumbia · mosott", r: 1, notes: "piros alma, karamell", p: 5400 },
      { id: "bra", n: "Brazília Cerrado", o: "Brazília · natúr", r: 2, notes: "mogyoró, étcsokoládé", p: 4900 },
      { id: "esp", n: "Hétköznapi espresso", o: "Brazília + Kolumbia", r: 2, notes: "kakaó, melasz, krémes test", p: 5200 },
    ],
    size: "250 g", cur: "HUF", freeAt: 15000,
    cart: "Kosár", empty: "Még üres a kosarad.", freeLeft: "Még {x} az ingyenes szállításig", freeOk: "Ingyenes szállítás ✓",
    total: "Összesen", checkout: "Tovább a pénztárhoz", checkoutNote: "Bemutató: itt nem lehet fizetni.", close: "Bezárás", remove: "Eltávolítás",
    trackTag: "Ügyfélszolgálat", trackTitle: "Hol a csomagom?", trackSub: "Írd be a rendelésszámot, és az ügyfélszolgálati agent azonnal válaszol — éjjel is.",
    trackPh: "pl. ORL-1042", trackBtn: "Keresés", trackHint: "Próbáld ki: ORL-1042",
    steps: ["Megrendelve", "Pörkölve", "Csomagolva", "Futárnál", "Kézbesítve"],
    agent: "Szia! Az ORL-1042 rendelésed ma reggel került a futárhoz, holnap 10 és 14 óra között érkezik. A követési linket SMS-ben is elküldtem. Segíthetek még valamiben?",
    notFound: "Ilyen rendelésszámot nem találtam. A bemutatóban az ORL-1042 működik.",
    badge: "Ezt az ügyfélszolgálatot az AXIMBRA AI-agentje viszi",
    subTitle: "Előfizetés: soha ne fogyj ki", subText: "Kéthetente vagy havonta, bármikor lemondható. Minden szállítmányból 10% kedvezmény.", subCta: "Érdekel az előfizetés",
    perks: ["48 órán belül pörkölve", "Visszaküldés 14 napig", "Biztonságos fizetés"],
    address: "1095 Budapest, Képzelt rakpart 9.", email: "hello@orlo-demo.hu",
  },
  en: {
    heroAgent: "Try the AI customer service",
    liveStep1: "1. Place a test order to your own email address", liveOrderBtn: "Place test order", liveOrdering: "Ordering…",
    liveOrdered: "Done: order {n} was placed for {e}. Now ask the agent where it is!",
    liveStep2: "2. Write to customer service", liveAsk: "Hi! Where is my order {n}?", liveStranger: "Try it from another address too", liveOther: "Sample messages",
    liveTag: "Live AI agent", liveTitle: "Write to customer service", liveSub: "This is no longer a scripted demo: the real AXIMBRA web-shop agent reads your message, finds the order and drafts the reply. In a live shop, a team member would approve it.",
    liveFrom: "Sender email", liveMsg: "Message", liveSend: "Send", liveSending: "The agent is working…",
    liveDraft: "The agent's draft reply", liveOk: "Verified customer", liveNo: "Not the ordering address – no details shared", liveNone: "No such order",
    liveHuman: "Needs a human", liveErr: "I can't reach the agent right now. Try again in a minute.",
    liveHint: "Try it: with the ordering address you get the parcel details, with any other address you don't.",
    liveSamples: [["anna.kovacs@example.com", "Hi! Where is my order ORL-1042? I need it for a gift tomorrow."], ["someone@gmail.com", "Where is order ORL-1042?"], ["peter.nagy@example.com", "I'd like to return order ORL-1043, how do I do that?"]],
    seo: { title: "ŐRLŐ coffee roasters — AXIMBRA demo shop", description: "A demo web shop for an invented coffee roaster: roast slider, cart, order tracking with an AI support agent. Built by AXIMBRA." },
    brand: "ŐRLŐ", brandSub: "coffee roasters",
    ship: "Free shipping over {x} · roasted and sent within 48 hours",
    eyebrow: "Specialty coffee · roasted in small batches",
    title: "Freshly roasted. At your door tomorrow.",
    sub: "From traceable farms, roasted weekly, posted within 48 hours of roasting.",
    cta: "Choose a coffee", ghost: "Where's my parcel?",
    roastTag: "Flavour finder", roastTitle: "How do you like your roast?", roastSub: "Move the slider — we'll show the tasting notes and the coffee that suits you.",
    roasts: [
      { n: "Light", notes: ["jasmine", "citrus", "black tea"], hint: "For filter: a clean, fruity cup." },
      { n: "Medium", notes: ["caramel", "apple", "milk chocolate"], hint: "Good for everything: filter, moka, milk drinks." },
      { n: "Dark", notes: ["dark chocolate", "walnut", "molasses"], hint: "For espresso and milk drinks: full-bodied and sweet." },
    ],
    match: "We recommend:",
    shopTitle: "This week's roast", add: "Add to cart", added: "Added",
    products: [
      { id: "eti", n: "Ethiopia Guji", o: "Ethiopia · washed", r: 0, notes: "peach, jasmine, bergamot", p: 16.9 },
      { id: "kol", n: "Colombia Huila", o: "Colombia · washed", r: 1, notes: "red apple, caramel", p: 15.5 },
      { id: "bra", n: "Brazil Cerrado", o: "Brazil · natural", r: 2, notes: "hazelnut, dark chocolate", p: 13.9 },
      { id: "esp", n: "Everyday espresso", o: "Brazil + Colombia", r: 2, notes: "cocoa, molasses, creamy body", p: 14.9 },
    ],
    size: "250 g", cur: "EUR", freeAt: 40,
    cart: "Cart", empty: "Your cart is empty.", freeLeft: "{x} away from free shipping", freeOk: "Free shipping ✓",
    total: "Total", checkout: "Go to checkout", checkoutNote: "Demo: no payment is possible here.", close: "Close", remove: "Remove",
    trackTag: "Customer service", trackTitle: "Where's my parcel?", trackSub: "Type your order number and the support agent answers instantly — at night too.",
    trackPh: "e.g. ORL-1042", trackBtn: "Search", trackHint: "Try: ORL-1042",
    steps: ["Ordered", "Roasted", "Packed", "With courier", "Delivered"],
    agent: "Hi! Your order ORL-1042 was handed to the courier this morning and arrives tomorrow between 10:00 and 14:00. I've also texted you the tracking link. Anything else I can help with?",
    notFound: "I couldn't find that order number. In this demo, ORL-1042 works.",
    badge: "This customer service is run by an AXIMBRA AI agent",
    subTitle: "Subscribe and never run out", subText: "Every two weeks or monthly, cancel any time. 10% off every delivery.", subCta: "Tell me about subscriptions",
    perks: ["Roasted within 48 hours", "14-day returns", "Secure payment"],
    address: "Imaginary Quay 9, 1095 Budapest", email: "hello@orlo-demo.hu",
  },
  de: {
    heroAgent: "KI-Kundenservice testen",
    liveStep1: "1. Geben Sie eine Testbestellung an Ihre eigene E-Mail-Adresse auf", liveOrderBtn: "Testbestellung aufgeben", liveOrdering: "Bestellung läuft…",
    liveOrdered: "Fertig: Bestellung {n} für {e} wurde aufgegeben. Fragen Sie den Agenten jetzt, wo sie ist!",
    liveStep2: "2. Schreiben Sie dem Kundenservice", liveAsk: "Guten Tag, wo ist meine Bestellung {n}?", liveStranger: "Auch mit einer anderen Adresse testen", liveOther: "Beispielnachrichten",
    liveTag: "Live-KI-Agent", liveTitle: "Schreiben Sie dem Kundenservice", liveSub: "Das ist kein vorgefertigter Text mehr: Der echte AXIMBRA-Webshop-Agent liest Ihre Nachricht, findet die Bestellung und schreibt den Antwortentwurf. In einem echten Shop gibt ihn ein Mitarbeiter frei.",
    liveFrom: "Absender-E-Mail", liveMsg: "Nachricht", liveSend: "Senden", liveSending: "Der Agent arbeitet…",
    liveDraft: "Antwortentwurf des Agenten", liveOk: "Kunde verifiziert", liveNo: "Nicht die Bestelladresse – keine Daten herausgegeben", liveNone: "Keine solche Bestellung",
    liveHuman: "Mitarbeiter prüft", liveErr: "Der Agent ist gerade nicht erreichbar. Bitte in einer Minute erneut versuchen.",
    liveHint: "Probieren Sie es: Mit der Bestelladresse erhalten Sie die Sendungsdaten, mit einer anderen nicht.",
    liveSamples: [["anna.kovacs@example.com", "Guten Tag, wo ist meine Bestellung ORL-1042? Ich brauche sie morgen als Geschenk."], ["jemand@gmail.com", "Wo ist die Bestellung ORL-1042?"], ["peter.nagy@example.com", "Ich möchte die Bestellung ORL-1043 zurückgeben. Wie geht das?"]],
    seo: { title: "ŐRLŐ Kaffeerösterei — AXIMBRA Demo-Shop", description: "Demo-Webshop einer erfundenen Kaffeerösterei: Röstgrad-Regler, Warenkorb, Sendungsverfolgung mit KI-Kundenservice. Erstellt von AXIMBRA." },
    brand: "ŐRLŐ", brandSub: "Kaffeerösterei",
    ship: "Versandkostenfrei ab {x} · innerhalb von 48 Stunden geröstet und verschickt",
    eyebrow: "Specialty Coffee · in kleinen Chargen geröstet",
    title: "Frisch geröstet. Morgen bei Ihnen.",
    sub: "Von rückverfolgbaren Farmen, wöchentlich geröstet, innerhalb von 48 Stunden nach der Röstung verschickt.",
    cta: "Kaffee auswählen", ghost: "Wo ist mein Paket?",
    roastTag: "Geschmacksfinder", roastTitle: "Welcher Röstgrad schmeckt Ihnen?", roastSub: "Bewegen Sie den Regler — wir zeigen die Aromen und den passenden Kaffee.",
    roasts: [
      { n: "Hell", notes: ["Jasmin", "Zitrus", "Schwarztee"], hint: "Für Filterkaffee: klar und fruchtig." },
      { n: "Mittel", notes: ["Karamell", "Apfel", "Milchschokolade"], hint: "Für alles: Filter, Mokka, Milchgetränke." },
      { n: "Dunkel", notes: ["Zartbitter", "Walnuss", "Melasse"], hint: "Für Espresso und Milchgetränke: vollmundig und süß." },
    ],
    match: "Unsere Empfehlung:",
    shopTitle: "Die Röstung dieser Woche", add: "In den Warenkorb", added: "Hinzugefügt",
    products: [
      { id: "eti", n: "Äthiopien Guji", o: "Äthiopien · gewaschen", r: 0, notes: "Pfirsich, Jasmin, Bergamotte", p: 16.9 },
      { id: "kol", n: "Kolumbien Huila", o: "Kolumbien · gewaschen", r: 1, notes: "roter Apfel, Karamell", p: 15.5 },
      { id: "bra", n: "Brasilien Cerrado", o: "Brasilien · natural", r: 2, notes: "Haselnuss, Zartbitter", p: 13.9 },
      { id: "esp", n: "Alltags-Espresso", o: "Brasilien + Kolumbien", r: 2, notes: "Kakao, Melasse, cremiger Körper", p: 14.9 },
    ],
    size: "250 g", cur: "EUR", freeAt: 40,
    cart: "Warenkorb", empty: "Ihr Warenkorb ist leer.", freeLeft: "Noch {x} bis zum kostenlosen Versand", freeOk: "Kostenloser Versand ✓",
    total: "Summe", checkout: "Zur Kasse", checkoutNote: "Demo: Hier ist keine Zahlung möglich.", close: "Schließen", remove: "Entfernen",
    trackTag: "Kundenservice", trackTitle: "Wo ist mein Paket?", trackSub: "Bestellnummer eingeben — der Service-Agent antwortet sofort, auch nachts.",
    trackPh: "z. B. ORL-1042", trackBtn: "Suchen", trackHint: "Probieren Sie: ORL-1042",
    steps: ["Bestellt", "Geröstet", "Verpackt", "Beim Kurier", "Zugestellt"],
    agent: "Hallo! Ihre Bestellung ORL-1042 ist heute Morgen an den Kurier gegangen und kommt morgen zwischen 10 und 14 Uhr. Den Tracking-Link habe ich Ihnen auch per SMS geschickt. Kann ich sonst noch helfen?",
    notFound: "Diese Bestellnummer habe ich nicht gefunden. In der Demo funktioniert ORL-1042.",
    badge: "Diesen Kundenservice führt ein KI-Agent von AXIMBRA",
    subTitle: "Im Abo nie wieder ohne Kaffee", subText: "Alle zwei Wochen oder monatlich, jederzeit kündbar. 10 % Rabatt auf jede Lieferung.", subCta: "Abo ansehen",
    perks: ["Innerhalb von 48 Stunden geröstet", "14 Tage Rückgabe", "Sichere Zahlung"],
    address: "Musterkai 9, 1095 Budapest", email: "hallo@orlo-demo.hu",
  },
};
export default webshop;
